### ISSUE TITLE
סגירת תפריט במובייל

### ISSUE THREAD

**Issue by MatveyMirman** [MatveyMirman/Erez-Itay-Project#2]
צריך ללחוץ על הכפתור כדי לסגור את התפריט במקום גרירה

**Comment by itay1221** [comment]
האופציה היחידה כרגע בגלל שהמטריאליז מפגר זה אם הלינקים בתפריט יוגדרו כ
href
במקום routerLink
ואז זה ירפרש את הדף

**Comment by MatveyMirman** [comment]
תפריט במובייל מוחלף בעקבות מעבר ל
MDB
